name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: ls -l ./demoforgit
    - run: mvn --file ./demoforgit/pom.xml --batch-mode --update-snapshots verify
    - run: mkdir ./demoforgit/staging && cp ./demoforgit/target/*.jar ./demoforgit/staging
    - uses: actions/upload-artifact@v4
      with:
        name: demoforgit-jar
        path: ./demoforgit/staging/*.jar
    - uses: actions/download-artifact@v4
      with:
        name: demoforgit-deploy
        #path: ./demoforgit/staging/*.jar
        run: ls -l
